run: 
	go run cmd/sso/main.go --config=./config/local.yaml

# Запуск миграция
# go run ..cmd/migrator/ --storage-path=./storage/sso.db --migratio
# ns-path=./migrations 

.DEFAULT_GOAL := run
.PHONY: run